# Faça um programa que leia um numero inteiro qualquer e mostre na tela sua tabuada

n = int(input('Digite um numero '))
print('Aqui está a tabuada de {}'.format(n))
print('-' *12)
print('{} X 1 = {}'.format(n, n*1))
print('{} X 2 = {}'.format(n, n*2))
print('{} X 3 = {}'.format(n, n*3))
print('{} X 4 = {}'.format(n, n*4))
print('{} X 5 = {}'.format(n, n*5))
print('{} X 6 = {}'.format(n, n*6))
print('{} X 7 = {}'.format(n, n*7))
print('{} X 8 = {}'.format(n, n*8))
print('{} X 9 = {}'.format(n, n*9))
print('{} X 10 = {}'.format(n, n*10))
print('-' *12)